// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhV5l5Vs6PX-AZxhHDORJ-uIzT6xicVo',
    appId: '1:787005205099:web:ad5401d967ffc845fc5f2e',
    messagingSenderId: '787005205099',
    projectId: 'ecommerceapp-e184b',
    authDomain: 'ecommerceapp-e184b.firebaseapp.com',
    storageBucket: 'ecommerceapp-e184b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfzPn2AgOIV3bk3mltNdRQgo9W4jZ4tUc',
    appId: '1:787005205099:android:ada3a9283f91c158fc5f2e',
    messagingSenderId: '787005205099',
    projectId: 'ecommerceapp-e184b',
    storageBucket: 'ecommerceapp-e184b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvLUpRjwj__J5rElYEBJdabKxKmNv0gmc',
    appId: '1:787005205099:ios:ec331a896ddb8f29fc5f2e',
    messagingSenderId: '787005205099',
    projectId: 'ecommerceapp-e184b',
    storageBucket: 'ecommerceapp-e184b.appspot.com',
    iosClientId: '787005205099-7v73ofkuf3jo6q8estsg6fq03n6nt1v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvLUpRjwj__J5rElYEBJdabKxKmNv0gmc',
    appId: '1:787005205099:ios:ec331a896ddb8f29fc5f2e',
    messagingSenderId: '787005205099',
    projectId: 'ecommerceapp-e184b',
    storageBucket: 'ecommerceapp-e184b.appspot.com',
    iosClientId: '787005205099-7v73ofkuf3jo6q8estsg6fq03n6nt1v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFhV5l5Vs6PX-AZxhHDORJ-uIzT6xicVo',
    appId: '1:787005205099:web:b906dbe051c82fe5fc5f2e',
    messagingSenderId: '787005205099',
    projectId: 'ecommerceapp-e184b',
    authDomain: 'ecommerceapp-e184b.firebaseapp.com',
    storageBucket: 'ecommerceapp-e184b.appspot.com',
  );

}